namespace Ignite.ExpertFinder.Contract
{
    public enum Skills
    {
        DataPlatformAndAnalytics,
        EnterpriseMobility,
        DataCenterSystemCenter,
        DataCenterWindowsServer,
        Devices,
        DynamicsCRMCRMOnPremise,
        DynamicsERPNAVSMB,
        ECSLicensing,
        EMSIdentityandAccessManagementActiveDirectory,
        EMSUnifiedDeviceManagementIntune,
        EnterpriseCloudSuiteEMS,
        Office365Exchange,
        SQLServer,
        Win10DeploymentManagementIdentitySecurity,
        AzureDataPlatformAnalytics,
        AzureEnterpriseMobilityHybridIDAccess,
        AzureIOTInternetOfThings,
        AzureModernAppDeveloperCloudAppService,
        AzureModernAppMediaSolutions,
        AzureModernAppMobileEngagement,
        AzureModernDCBusinessContinuityDisasterRecovery,
        AzureModernDCCloudCompute,
        AzureModernDCHybridCloudManagement,
        AzureModernDCHybridStorage,
        AzureModernDCSecurityCompliance,
        AzureModernDCVirtualNetwork
    }
}
